### ISSUE TITLE
How to apply one theme to all plots in ggplot?

### ISSUE THREAD

**Issue by csbailey5t** [NCSU-Libraries/data-science-cookbook#1]

**Comment by SRSchmittling** [comment]
@csbailey5t I believe I worked through this with a patron.  I'll can locate the code and make a more general example.

**Comment by SRSchmittling** [comment]
I created a recipe for this. Will push my branch to git as soon as I figure out why I can authenticate...

**Comment by csbailey5t** [comment]
Fixed in cf1c3fdd7c547323e893b7777003079810a8ce87
