### ISSUE TITLE
.gitignore file and ignoring previously committed .

### ISSUE THREAD

**Issue by mikenutt** [NCSU-Libraries/data-science-cookbook#23]
regarding .DS_Store files like this: https://github.com/NCSU-Libraries/data-science-cookbook/blob/main/.DS_Store

I think these are created by GitHub Desktop for Mac OS. @csbailey5t Any thoughts about a .gitignore file? 

And apparently we would need a rule to [ignore a previously committed file](https://www.atlassian.com/git/tutorials/saving-changes/gitignore)? 
`$ echo debug.log >> .gitignore $ git rm --cached debug.log rm 'debug.log' $ git commit -m "Start ignoring debug.log" `

**Comment by csbailey5t** [comment]
.DS_Store files are artifacts of MacOS often generated when opening a directory in Finder. 

Fixed in b11fe35afe070e710f3c032635b14515570c485e
