### ISSUE TITLE
How to modify and existing or create a new theme for ggplots in R

### ISSUE THREAD

**Issue by SRSchmittling** [NCSU-Libraries/data-science-cookbook#9]
A recipe for using theme_update() and theme_replace() with ggplot

**Comment by mikenutt** [comment]
How would this differ from the documentation at https://ggplot2.tidyverse.org/reference/theme_get.html?

**Comment by SRSchmittling** [comment]
This recipe would show what is different between theme_update() and theme_replace().  The link references the difference, but it isn't clear from a programatic perspective, how these are different. The examples would allow users to "see" the difference.

**Comment by SRSchmittling** [comment]
Can this issue be closed? I would say that the recipe would be an improvement [over the link](https://ggplot2.tidyverse.org/reference/theme_get.html) by virtual of the fact that it will have an example, which makes the difference between theme_update() and theme_replace() more obvious.

**Comment by csbailey5t** [comment]
Agreed on the value of the recipe.
